crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from primary_docs.urls import v1_api as pd_api
from taskmaster.urls import v1_api as tm_api


urlpatterns = [
    url(r'^api/', include(tm_api.urls)),
    url(r'^api/', include(pd_api.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'', include('taskmaster.urls')),
]

taskmaster/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from tastypie.api import Api
from .api.resources import TaskResource, UserResource,  MessageResource, FileResource, BugReportResource, ChatResource


v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(TaskResource())
v1_api.register(MessageResource())
v1_api.register(ChatResource())
v1_api.register(FileResource())
v1_api.register(BugReportResource())


urlpatterns = [
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

taskmaster/models.py
from datetime import datetime
import os

from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager, AbstractBaseUser
from django.utils import timezone



from primary_docs.models import Organization, Station


# Path for save files / Путь сохранения файлов
def upload_file(instance, filename):
    return 'files/{0}/{1}'.format(instance.sender.username, filename)


# Important values for tasks / Уровни важности заданий
R = 'danger'
Y = 'warning'
G = 'success'

IMPORTANCE = (
    (R, 'высокая'),
    (Y, 'средняя'),
    (G, 'низкая')
)


# Custom user model / Измененная модель пользователя
class User(AbstractUser):
    third_name = models.CharField('Отчество', max_length=50)
    position = models.CharField('Должность', max_length=50)
    organization = models.ForeignKey(
        Organization, 
        on_delete=models.SET_NULL, 
        verbose_name='Организация',
        related_name='employees', 
        blank=True, null=True
    )
    station = models.ForeignKey(
        Station, 
        on_delete=models.SET_NULL, 
        verbose_name='Участок',
        related_name='employees', 
        blank=True, null=True
    )
    avatar = models.ImageField(
        verbose_name='Аватар',
        max_length=255, 
        upload_to='images/avatars/', 
        blank=True
    )

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'

    def get_full_name(self):
        return '{0} {1}. {2}.'.format(self.last_name, self.first_name[0], self.third_name[0])

    def __str__(self):
        if self.last_name and self.first_name and self.third_name:
            return self.get_full_name()
        return self.username


# Bug report model
class BugReport(models.Model):
    reporter = models.ForeignKey('User', related_name="reports", verbose_name="Отправитель")
    text = models.TextField('Описание', max_length=500)

    class Meta:
        verbose_name = 'Отчет об ошибке'
        verbose_name_plural = 'Отчеты об ошибках'

    def __str__(self):
        return 'Отчет № {}'.format(self.id)


# File model / Модель файла
class File(models.Model):
    title = models.CharField('Название', max_length=50, default=None)
    description = models.TextField(
        'Описание', max_length=255, blank=True, default=None, null=True)
    recipient = models.ManyToManyField(
        User, verbose_name='Получатель', related_name='received_files', blank=True)
    sender = models.ForeignKey(
        User, verbose_name='Отправитель', related_name='send_files', null=True, blank=True)
    file = models.FileField('Файл', max_length=255, upload_to=upload_file)

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'

    def __str__(self):
        return os.path.basename(self.file.name)

    def terminate(self):
        if os.path.exists(self.file.path):
            os.remove(self.file.path)
        self.delete()


@receiver(pre_delete, sender=File)
def delete_file(sender, instance, **kwargs):
    instance.file.delete(False)


# Task model / Модель заданий
class Task(models.Model):
    performer = models.ForeignKey(
        User, 
        verbose_name='Исполнитель', 
        related_name='tasks', 
        null=True, 
        default=User
        )
    assigner = models.ForeignKey(
        User, 
        verbose_name='Назначающий', 
        related_name='given_tasks', 
        null=True
        )

    importance = models.CharField(
        'Важность', 
        null=True, 
        choices=IMPORTANCE, 
        max_length=10
        )
    files = models.ManyToManyField(
        File, 
        verbose_name='Файлы', 
        related_name='task', 
        max_length=255, 
        blank=True
        )
    title = models.CharField('Название', max_length=50, default=None)
    text = models.TextField(
        'Описание', 
        max_length=350, 
        default=None, 
        null=True
        )
    created_date = models.DateTimeField('Созданно', default=timezone.now)
    completed_date = models.DateTimeField(
        'Выполнено', 
        default=None, 
        blank=True, 
        null=True
        )
    to_complete = models.DateTimeField(
        'Выполнить до', 
        default=None
        )
    is_completed = models.BooleanField('Завершено', default=False)
    viewed = models.BooleanField('Просмотренно', default=False)
    comment = models.TextField(
        'Комментарий', 
        max_length=500, 
        null=True, 
        blank=True
        )

    class Meta:
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'
        ordering = ['-to_complete']

    def __str__(self):
        return self.title

    def complete(self):
        self.is_completed = True
        self.completed_date = timezone.now()
        self.save()

    def get_status(self):
        if not self.is_completed:
            if self.to_complete > timezone.now():
                return 'in_process'
            else:
                return 'overdue'
        else:
            return 'completed'

    def get_style(self):
        if self.is_completed:
            return 'success'
        else:
            return 'danger'


# Message model / Модель сообщений
class Message(models.Model):
    title = models.CharField(verbose_name='Тема', max_length=50, default='Новое сообщение')
    text = models.TextField(verbose_name='Текст', max_length=500, default=None)

    files = models.ManyToManyField(
        File,
        verbose_name='Файлы',
        related_name='messages',
        blank=True
    )
    recipient = models.ManyToManyField(
        User, verbose_name='Кому', related_name='incoming_messages')
    sender = models.ForeignKey(
        User,
        verbose_name='Отправитель',
        related_name='outcoming_messages',
        null=True
    )
    created_date = models.DateTimeField('Созданно', default=timezone.now)
    is_new = models.BooleanField(verbose_name="Не прочитанное", default=True)

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ['-created_date']

    def __str__(self):
        return self.title

    def read(self):
        self.is_new = False
        self.save()

    def full_delete(self):
        for file in self.files.all():
            file.terminate()
        self.delete()


class Chat(models.Model):
    members = models.ManyToManyField(User, verbose_name="Участники", related_name="chats")
    messages = models.ManyToManyField(Message, verbose_name="Сообщения", related_name="chats")
    updated = models.DateTimeField(null=True)

    class Meta:
        verbose_name = 'Чат'
        verbose_name_plural = 'Чаты'
        ordering = ['-updated']

taskmaster/forms.py
from django import forms
from django.contrib.admin.widgets import AdminTimeWidget, AdminDateWidget

from .models import Task, Message, User


# Login form
class LoginForm(forms.Form):
    username = forms.CharField(label='Логин', max_length=40)
    password = forms.CharField(label='Пароль', max_length=40, widget=forms.PasswordInput())
    next = forms.CharField(widget=forms.HiddenInput(), required=False)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control text-center'


# Task form
class TaskForm(forms.ModelForm):
    files = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label='Файлы', required=False)

    field_order = ['performer','to_complete']

    class Meta:
        model = Task
        fields = (
            'performer', 'importance', 'title', 'to_complete',
            'text', 'comment'
            )

    def __init__(self, *args, **kwargs):
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['to_complete'].input_formats = ["%a %b %d %Y %H:%M:%S"]


# Message form
class MessageForm(forms.ModelForm):
    files = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}),
        label='Файлы', required=False)

    class Meta:
        model = Message
        fields = ('recipient', 'title', 'text')

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['text'].widget.attrs['rows'] = 5


# User form
class UserForm(forms.ModelForm):
    #password = forms.CharField(max_length=50, widget=forms.PasswordInput(), label="Пароль")

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'third_name',
            'username', 'password', 'email', 'position', 'avatar'
        )

taskmaster/views.py
# views

taskmaster/templates/taskmaster/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta name=viewport content="width=device-width,initial-scale=1">
		<script src='{% static "js/jquery-3.2.0.min.js" %}'></script>
		<script src='{% static "js/tether.js" %}'></script>
		<script src='{% static "js/bootstrap.js" %}'></script>
		<link rel="stylesheet" href='{% static "css/tether.css" %}'>
		<link rel="stylesheet" href='{% static "css/bootstrap.css" %}'>
		<link rel="stylesheet" href='{% static "css/style.css" %}'>
		<link rel="stylesheet" href='{% static "css/font-awesome.min.css" %}'>		
		<title>
			TaskMaster |
			{% block title %}
			{% endblock %}
		</title>
	</head>
	<body onload="startTime();">
		<div id="container" class="container d-flex justify-content-center align-items-stretch">
			<div class="card text-center" id="main">
				<div class="card-header p-0 text-left d-flex justify-content-between">
					<div id="logo" class="d-flex align-items-md-end align-items-sm-center justify-content-sm-center flex-md-row flex-sm-column">
						<div class="logo-image m-1"></div>
						<div class="logo-text h3 p-2">
							<a href='/' id="root-link">Тарасовское ГАУ РО "Лес"</a>
						</div>
					</div>
					<div class="card d-flex flex-row p-2 m-2" id="info">
						{% if user.avatar %}
							<img src="{{ user.avatar.url }}" id="avatar" class="rounded user-pic">
						{% else %}
							<img src="/media/users/avatars/user.png" id="avatar" class="rounded user-pic">
						{% endif %}
						<div class="d-flex flex-column justify-content-center ml-2 small align-items-between">
							<div class="d-flex justify-content-between m-1 d-block"><b>Имя</b><span>{{user.first_name}}</span></div>
							<div class="d-flex justify-content-between m-1"><b>Фамилия</b><span>{{user.last_name}}</div></span>
							<div class="d-flex justify-content-between m-1"><b>Отчество</b><span>{{user.third_name}}</div></span>
							<div class="d-flex justify-content-between m-1"><b>Должность</b><span>{{user.position}}</span></div>
							<div class="d-flex justify-content-between align-items-center pt-2 pb-2 m-1">
								<div id="date" class="pl-1 pr-1">{% now 'd m y D' %}</div>|
								<div id="clock" class="pl-1 pr-1"></div>|
								<a href="/logout" class="fa fa-sign-in text-primary pl-1 pr-1" data-toggle="tooltip" data-placement="left" title="Выход" role='button'></a>
							</div>
						</div>
					</div>
				</div>
				<nav class="navbar navbar-inverse bg-inverse">
					<ul class="nav nav-pills">
						<li class="nav-item">
							<a class="nav-link text-white btn-outline-danger" href="/">
							<i class="fa fa-home navbar-brand text-success"></i>
							На главную
							</a>
						</li>
						<li class="nav-item dropdown">
							<a class='nav-link dropdown-toggle text-white btn-outline-danger' href="/tasks/" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-tasks navbar-brand text-warning"></i>
									
								Задачи 
								{% with new_tasks=user.get_new_tasks %}
									{% if new_tasks > 0 %}
										<span class="badge badge-success" id="task_counter">{{ new_tasks }}</span>
									{% else %}
										<span class="badge badge-success" id="task_counter"></span>
									{% endif %}
									
								 {% endwith %}
							</a>
							<div class="dropdown-menu bg-inverse">
								<a class="dropdown-item" href="{% url 'create_task' %}">Создать задачу</a>
								<a class="dropdown-item" href="{% url 'get_tasks' dist='inc' %}?status=uncompleted">Мои задачи</a>
								<a class="dropdown-item" href="{% url 'get_tasks' dist='out' %}">Назначенные мною</a>
								{% if user.is_staff %}
									<div class="dropdown-divider"></div>
									<a class="dropdown-item" href="{% url 'get_tasks' dist='all' %}">Все задачи</a>
								{% endif %}
							</div>
						</li>
						<li class="nav-item dropdown">
							<a class='nav-link dropdown-toggle text-white btn-outline-danger' id="dropdownMenu" href="/messages/inbox/" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-envelope navbar-brand text-danger"></i>
								Сообщения
								{% with new_messages=user.get_new_messages %}
									{% if new_messages > 0 %}
										<span class="badge badge-success" id="message_counter">{{ new_messages }}</span>
									{% else %}
										<span class="badge badge-success" id="message_counter"></span>
									{% endif %}
								 {% endwith %}
							</a>
							<div class="dropdown-menu bg-inverse" aria-labelledby="dropdownMenu">
								<a class="dropdown-item" href="{% url 'get_messages' dist='inbox' %}">Входящие</a>
								<a class="dropdown-item" href="{% url 'get_messages' dist='sent' %}">Исходящие</a>
								<div class="dropdown-divider"></div>
								<a class="dropdown-item" role='button' id="newMessageButton" data-toggle="modal" data-target="#newMessageModal">Создать новое</a>
							</div>
								<div class="modal fade" id="newMessageModal" role="dialog">
								  <div class="modal-dialog" role="document">
									<div class="modal-content">
									  <div class="modal-header bg-success text-white">
										<h5 class="modal-title" id="new-message-title">Новое сообщение</h5>
										<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										  <span aria-hidden="true">&times;</span>
										</button>
									  </div>
									  <div class="modal-body">
											<form method="POST" enctype="multipart/form-data" id="new-message-form" action="/messages/new">
											{% csrf_token %}
											<input type="hidden" name='next' value="{{ request.path_info }}" >
											<div class="form-group">
											</div>
											</form>
									  </div>
									  <div class="modal-footer">
										<button type="submit" form="new-message-form" role="button" class="btn btn-success">Отправить</button>
										<button type="button" class="btn btn-danger" role="button" data-dismiss="modal">Закрыть</button>
										</div>
									  </div>
									</div>
								  </div>
						</li>
						<li class="nav-item">
							<a href="{% url 'get_employees' %}" class='nav-link text-white btn-outline-warning'>
								<i class="fa fa-users navbar-brand text-success"></i>Сотрудники</a>
						</li>
								<li class="nav-item dropdown">
							<a class='nav-link dropdown-toggle text-white btn-outline-danger' href="/docs/" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
								<i class="fa fa-file navbar-brand text-warning"></i>								
								Документы
							</a>
							<div class="dropdown-menu bg-inverse">
								<a class="dropdown-item" href="{% url 'waybills' %}">Путевые листы</a>
								<a class="dropdown-item" href="{% url 'new_outfit' %}">Наряд-акты</a>
							</div>
						</li>
					</ul>
				</nav>
				<div class="card-block p-0 pr-2 pl-2" id="content">
					{% block content %}
					{% endblock %}
				</div>
				<div class="card-footer bg-inverse flex-row mt-auto">
						<a href="/logout" class="btn btn-outline-danger text-white fa fa-sign-in" data-toggle="tooltip" data-placement="right" title="Выход" role='button'></a>
				</div>
			</div>
		</div>
	</body>
			<script src='{% static "js/main.js" %}'></script>
</html>

taskmaster/templates/taskmaster/create_task.html
{% extends 'taskmaster/base.html' %}

{% block title %}
	Создание задачи
{% endblock %}

{% block content %}
	<div class="card m-2 d-inline-flex card-outline-primary">
			<h4 class="card-header bg-primary text-white">
				Новая задача
			</h4>
		<div class="card-block bg-faded">
			<form method="POST" enctype="multipart/form-data" class="input-group-sm">
				{% csrf_token %}
				<div class="form-group">
					{{ form.as_p }}
					<button type="submit" role='button' class="btn btn-outline-success fa fa-check"><b class="ml-1">Сохранить</b></button>
				</div>
			</form>
		</div>
	</div>
{% endblock %}

taskmaster/templates/taskmaster/index.html
{% extends 'taskmaster/base.html' %}
{% block title %}
	{{ user.last_name }} {{user.first_name|first}}. {{ user.third_name|first}}.
{% endblock %}

{% block content %}
<div class="card">
	<div class="card-header table-responsive">
		<h5>Задачи на сегодня</h5>
	</div>
	
	<table class="table table-hover table-bordered">
		<thead>
			<th>№</th>
			<th>Опции</th>
			<th>Кому назначенно</th>
			<th>Кем назначенно</th>
			<th>Важность</th>
			<th>Выполнить до</th>
			<th>Название</th>
			<th>Статус</th>
		</thead>
		<tbody>
		{% for task in tasks %}
		<tr>
			<td>{{ forloop.counter }}</td>
			<td><a href="{% url 'task_view' pk=task.pk %}" class="fa fa-eye btn btn-sm btn-outline-primary border-0" role='button' data-toggle="tooltip" title="Просмотреть"></a></td>
			<td>{{ task.performer }}</td>
			<td>{{ task.assigner }}</td>
			<td><span class="badge badge-{{task.importance}}">{{ task.get_importance_display }}</span></td>
			<td>{{ task.to_complete }}</td>
			<td>{{ task.title }}</td>
			<td>{% if task.get_status == 'completed' %}
				<span class='fa fa-check text-success'></span>
				{% elif task.get_status == 'in_process' %}
					<span class='fa fa-hourglass text-warning'></span>
				{% elif task.get_status == 'overdue' %}
					<span class='fa fa-remove text-danger'></span>
				{% endif %}
			</td>
		{% endfor %}
		</tr>
		</tbody>
	</table>
</div>
{% endblock %}

taskmaster/templates/taskmaster/task.html
{% extends 'taskmaster/base.html' %}

{% block title %}
	Просмотр задания
{% endblock %}

{% block content %}
	<div class="d-flex justify-content-center p-3">
		{% if task.assigner == user or user.is_staff %}
		<div class="p-1 d-flex align-self-start flex-last flex-column align-items-stretch rounded-right table-bordered">
			<button class="m-1 btn btn-outline-primary fa fa-edit" role='button' data-toggle="modal" data-target="#taskModal"></button>
			<div class="modal fade" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
			  <div class="modal-dialog">
				<div class="modal-content">
				  <div class="modal-header">
					<h5 class="modal-title" id="exampleModalLabel">Редактирование задачи</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					  <span aria-hidden="true">&times;</span>
					</button>
				 </div>
			    <div class="modal-body">
					<form id="task-form" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					{{ form.as_p }}
					<div id="files" class="card">
						{% for file in task.files.all %}
							<span class="d-flex justify-content-between align-items-center p-2 table-hover">{{ file }}<button type='button' onclick='removeFile({{file.pk}});' class="btn btn-secondary fa fa-remove text-danger" id="remove-file-btn"></button></span>
						{% endfor %}
					</div>
					</form>
				</div>
				<div class="modal-footer">
					<button type="submit" form="task-form" class="btn btn-success">Сохранить</button>
					<button type="button" class="btn btn-danger" data-dismiss="modal">Отмена</button>
				</div>
			  </div>
		    </div>
	      </div>
	      <button class='m-1 btn btn-outline-danger fa fa-remove' role='button' data-container='body' data-placement='top' data-trigger="focus" data-html='true' data-toggle='popover' title="Удалить?" data-content='<a href="{% url 'delete_task' pk=task.pk %}" class="p-2 fa fa-check text-danger"></a><a class="p-2 fa fa-remove text-success" role="button"></a>'></button> 
			{% if task.performer == user and not task.is_completed %}
			<button class="m-1 btn btn-outline-success fa fa-check" role='button' id="task_completed" onclick="taskComplete({{task.pk}});" data-toggle='tooltip' title="Отметить как выполненное"></button>
			{% endif %}
			</div>
			{% elif task.performer == user and not task.is_completed %}
			<div class="p-1 d-flex align-self-start flex-last flex-column align-items-stretch rounded-right table-bordered">
				<button class="m-1 btn btn-outline-success fa fa-check self-align-end" role='button' id="task_completed" onclick="taskComplete({{task.pk}});" data-toggle='tooltip' title="Отметить как выполненное"></button>
			</div>
		{% endif %}

<div class="card d-flex p-1">
	<table class="table table-hover table-bordered">
		<thead>
			<tr>
				<th class="p-2 text-center table-info" colspan='2'>{{ task.title }}</th>

			</tr>
		</thead>
		<tbody class='p-0'>
			<colgroup span='2' width='300'>
			<tr>
				<th>Важность</th>
				<td>
					<span class="badge badge-{{ task.importance }}" >{{ task.get_importance_display }}</span>
				</td>
			</tr>
			<tr>
				<th>Выполнить до</th>
				<td>{{ task.to_complete }}</td>
			</tr>
			<tr>
				<th>Назначающий</th>
				<td>{{ task.assigner.get_full_name }}</td>
			</tr>
			<tr>
				<th>Выполняющий</th>
				<td>{{ task.performer.get_full_name }}</td>
			</tr>
			<tr>
				<th>Дата создания</th>
				<td>{{ task.created_date }}</td>
			</tr>
			<tr>
				<th>Статус</th>
				<td>
				{% if task.get_status == 'completed' %}
					<span class='fa fa-check text-success'></span>
				{% elif task.get_status == 'in_process' %}
					<span class='fa fa-hourglass text-warning'></span>
				{% elif task.get_status == 'overdue' %}
					<span class='fa fa-remove text-danger'></span>
				{% endif %}
				</td>
			</tr>		
			<tr>
				<th>Дата выполнения</th>
				<td>{% if task.is_completed %} 
						{{ task.completed_date }}
					{% else %}
							---
					{% endif %}
				</td>
			</tr>
			<tr>
				<th>Прикрепленные файлы</th>
				<td>
					{% for file in task.files.all %}
						<a href="{{ file.file.url }}" class="fa fa-file" data-toggle='tooltip' title="{{ file.title }}" ></a>
					{% empty %}
						Нет
					{% endfor %}
				</td>
			</tr>
			<tr class='table-info'>
				<th colspan='2'>Описание задачи</th>
			</tr>	
			<tr class="text-left">
				<td colspan='2' class="p-2 table-bordered bg-default">{{ task.text }}</td>
			</tr>
		</tbody>
	</table>

	</div>
	</div>

{% endblock %}

taskmaster/templates/taskmaster/tasks.html
{% extends 'taskmaster/base.html' %}

{% block title %}
	{{ title }}
{% endblock %}

{% block content %}
	<div class="d-flex justify-content-center p-2 align-items-center">
		<div class="mr-auto ml-5">
			<a class="btn btn-outline-danger fa fa-thumbs-down" data-toggle="tooltip" title="Не выполненные задачи" href='?status=uncompleted'></a>
			<a class="btn btn-outline-success fa fa-thumbs-up" data-toggle="tooltip" title="Выполненные задачи" href='?status=completed'></a>
		</div>	
		<div class="m-auto"><b>{{title}}</b></div>
		<div class="">
			<form method="GET" action="{{request.path_info}}" class='form-inline form-control-sm'>
				<div class="form-group">
					<div class="input-group-sm d-inline-flex align-items-center">
						<div class="input-group-sm d-flex flex-column align-items-end mr-2">
							<span class="fa fa-check text-success">
								<input type='radio' value="completed" name="status" data-toggle='tooltip' title="Выполненные">
							</span>
							<span class="fa fa-exclamation text-danger">
								<input type='radio' value="uncompleted" name="status" data-toggle='tooltip' title="Не выполненные">
							</span>
						</div>
					<input type="date" name='date' class='form-control mr-2' required>
					<input type="time" name='time' class='form-control'>
					<button type="submit" data-toggle="tooltip" title="Отфильтровать" class='fa fa-filter form-control btn btn-outline-success cursor-pointer ml-2'></button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="table-responsive">
	<table class="table table-hover table-bordered">
	<style type="text/css">.table th{vertical-align: middle;};</style>
		<thead>
			<tr>
				<th>№</th>
				<th class='text-center'>Операции</th>
				<th class='text-center'>Важность</th>
				<th class='text-center'>Статус</th>
				<th class='text-center'>Назначающий</th>
				<th class='text-center'>Исполнитель</th>
				<th class='text-center'>Выполнить до</th>
				<th class='text-center'>Назначенно</th>
				<th class='text-center'>Заголовок</th>
				<th class='text-center'>Файлы</th>
			</tr>
		</thead>
		<tbody>
	{% for task in tasks %}
		<tr class="">
			<th scope="row">{{ forloop.counter }}</th>
			<td>
				<a href="{% url 'task_view' pk=task.pk %}" class="rounded btn-outline-primary border-0 fa fa-eye p-1" data-toggle='tooltip' title="Просмотреть"></a>
				{% if task.assigner == user or user.is_staff %}
				<button class="rounded btn-outline-danger border-0" role='button' data-container='body' data-placement='top' data-trigger="focus" data-html='true' data-toggle='popover' title="Удалить?" data-content="<span role='button' onclick='taskRemove({{task.pk}});' class='p-2 fa fa-check text-success'></span><span class='p-2 fa fa-remove text-danger' role='button'></span>">
					<span class="fa fa-trash" data-toggle="tooltip" title="Удалить"></span>
				</button>
			{% endif %}
			{% if task.performer == user and not task.is_completed %}
				<button class="rounded btn-outline-success border-0 fa fa-check" role="button" onclick="taskComplete({{task.pk}});" data-toggle="tooltip" title="Отметить как выполненное"></button>
			{% endif %}
			</td>
			<td><span class="badge badge-{{task.importance}}">{{ task.get_importance_display }}</span></td>
			<td>{% if task.get_status == 'completed' %}
					<span class='fa fa-check text-success'></span>
				{% elif task.get_status == 'in_process' %}
					<span class='fa fa-hourglass text-warning'></span>
				{% elif task.get_status == 'overdue' %}
					<span class='fa fa-remove text-danger'></span>
				{% endif %}
			</td>
			<td>{{ task.assigner.get_full_name }} </td>
			<td>{{ task.performer.get_full_name }} </td>
			<td>{{ task.to_complete }}</td>
			<td>{{ task.created_date }}</td>
			<td>{{ task.title|truncatewords:2}}</td>
			<td>{{ task.files.count }}</td>
		</tr>
	{% endfor %}
	</tbody>
	</table>
	</div>
{% endblock %}