crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from primary_docs.urls import v1_api as pd_api
from taskmaster.urls import v1_api as tm_api


urlpatterns = [
    url(r'^api/', include(tm_api.urls)),
    url(r'^api/', include(pd_api.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'', include('taskmaster.urls')),
]

primary_docs/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from . import views

from tastypie.api import Api

from .api import resources

v1_api = Api(api_name='v1')
v1_api.register(resources.OrganizationResource())
v1_api.register(resources.StationResource())
v1_api.register(resources.UnitsResource())
v1_api.register(resources.CarResource())
v1_api.register(resources.WorkerResource())
v1_api.register(resources.WayBillResource())
v1_api.register(resources.OutfitEventResource())
v1_api.register(resources.OutfitResource())
v1_api.register(resources.TractorRegFormWorkResource())
v1_api.register(resources.TractorRegFormResource())
v1_api.register(resources.SvodnayaZapisResource())
v1_api.register(resources.SvodnayaVedomostResource())
v1_api.register(resources.NakopitelnayaVedomostResource())
v1_api.register(resources.WorkTimeEntryResource())
v1_api.register(resources.WorkTimeTableResource())
v1_api.register(resources.MaterialCategoryResource())
v1_api.register(resources.MaterialResource())
v1_api.register(resources.ForestArrivalReportResource())
v1_api.register(resources.OutfitPostingResource())
v1_api.register(resources.OutfitExpenseResource())
v1_api.register(resources.RecyclingListResource())
v1_api.register(resources.HandoutResource())
v1_api.register(resources.FuelDistributionResource())
v1_api.register(resources.ActSpisanyaResource())


urlpatterns = [

]

taskmaster/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

from tastypie.api import Api
from .api.resources import TaskResource, UserResource,  MessageResource, FileResource, BugReportResource, ChatResource


v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(TaskResource())
v1_api.register(MessageResource())
v1_api.register(ChatResource())
v1_api.register(FileResource())
v1_api.register(BugReportResource())


urlpatterns = [
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

primary_docs/models.py
import json

from django.utils import timezone
from django.db import models
from django.db.models import Q
from django.conf import settings
from django.dispatch import receiver
from django.core.serializers.json import DjangoJSONEncoder

from jsonfield import JSONField


# Departaments / Отделы
DEPARTAMENTS = (
        ('les', 'Лес'),
        ('ceh', 'Цех'),
        ('phs', 'ПХС'),
        ('mtm', 'МТМ')
    )


# Fuel distribution types / Типы отчетов распределения ГСМ
CHOICES_OF_FUEL_DISTRIBUTION = (
    ('OF', 'Наряд-акт'),
    ('WB', 'Путевой лист'),
    ('TR', 'Учетный лист тракториста'),
)

# Types of venichle / Типы транспортных устройств
CHOICES_OF_KIND = (
        ('L', 'Легковой'),
        ('H', 'Грузовой'),
        ('T', 'Трактор'),
        ('C', 'Цистерна'),
        ('S', 'Шасси'),
        ('P', 'Прицеп'),
    )

# Organization model / Модель организации
class Organization(models.Model):
    head = models.ForeignKey(
        'primary_docs.Worker',
        related_name="organization_head",
        verbose_name="Руководитель",
        null=True,
        on_delete=models.SET_NULL,
        blank=True
        )
    name = models.CharField('Название', max_length=150)
    description = models.TextField('Полное название', max_length=250, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Организация'
        verbose_name_plural = 'Организации'


class Units(models.Model):
    short = models.CharField('Название', max_length=50, unique=True, null=True)
    name = models.CharField('Описание', max_length=50, null=True)

    class Meta:
        verbose_name = 'Еденица измерения'
        verbose_name_plural = 'Еденицы измерения'

    def __str__(self):
        return self.name


# Model of positions / Модель должностей
class Position(models.Model):
    name = models.CharField('Название', max_length=50, unique=True)

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'

    def __str__(self):
        return self.name


# Model of station / Модель участка
class Station(models.Model):
    name = models.CharField('Наименование участка', max_length=250)
    series = models.IntegerField('Серия')
    organization = models.ForeignKey(
        Organization,
        related_name='stations',
        verbose_name='Организация',
        null=True,
        on_delete=models.SET_NULL
    )
    head = models.ForeignKey(
        'primary_docs.Worker',
        related_name='sub_stations',
        verbose_name='Начальник участка',
        on_delete=models.SET_NULL,
        null=True, blank=True
    )
    masters = models.ManyToManyField(
        'primary_docs.Worker',
        related_name='master_of_stations',
        verbose_name='Мастер участка',
        blank=True
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Участок'
        verbose_name_plural = 'Участки'


# Model of worker / Модель работника
class Worker(models.Model):
    LEVELS = (
        ('1', 'Начальники'),
        ('2', 'Мастера'),
        ('3', 'Рабочие'),
    )
    surname = models.CharField('Фамилия', max_length=50)
    name = models.CharField('Имя', max_length=50)
    patronymic = models.CharField('Отчество', max_length=50)
    position = models.ForeignKey(
            Position,
            related_name="workers",
            verbose_name="Должность",
            null=True,
            on_delete=models.PROTECT
        )
    level = models.CharField(
        'Категория должности',
        max_length=50,
        choices=LEVELS,
        default=3,
        null=True
    )
    rank = models.IntegerField('Разряд', blank=True, null=True)
    station = models.ForeignKey(
        Station,
        related_name='workers',
        verbose_name='Участок',
        null=True,
        on_delete=models.PROTECT
    )

    def __str__(self):
        return self.surname + ' ' + self.name + ' ' + self.patronymic

    @property
    def get_full_name(self):
        return '{} {} {}'.format(self.surname, self.name, self.patronymic)

    @property
    def get_short_full_name(self):
        return '{} {}.{}.'.format(self.surname, self.name[0], self.patronymic[0])

    def get_position(self):
        return self.position.name

    class Meta:
        verbose_name = 'Работник'
        verbose_name_plural = 'Работники'
        ordering = ['surname']


# Model of fuel / Модель топлива
class Fuel(models.Model):
    mark = models.CharField(
        'Марка топлива',
        max_length=50
    )
    code = models.CharField(
        'Код топдива',
        max_length=50,
        blank=True,
        null=True,
    )
    price = models.DecimalField(
        'Цена за литр',
        max_digits=5,
        decimal_places=2,
        null=True
    )

    def __str__(self):
        if self.code:
            return '{} - {}'.format(self.mark, self.code)
        return self.mark

    def get_full(self):
        return self.__str__()

    class Meta:
        verbose_name = 'Топливо'
        verbose_name_plural = 'Топливо'


# Model of car / Модель автомобиля
class Car(models.Model):
    kind = models.CharField(
        'Тип автомобиля',
        choices=CHOICES_OF_KIND,
        max_length=50,
        null=True
    )
    name = models.CharField(
        'Марка автомобиля',
        max_length=50
    )
    number = models.CharField(
        'Государственный номерной знак',
        max_length=50,
        blank=True,
        null=True
    )
    status = models.BooleanField(
        'Исправен',
        default=True
    )
    available = models.BooleanField('Доступный', default=True)
    mileage = models.IntegerField('Показания спидометра', default=0)
    rate_normal_s = models.FloatField('Расход топлива, лето, норм. усл', default=0)
    rate_hard_s = models.FloatField('Расход топлива лето, тяж. усл', default=0)
    rate_normal_w = models.FloatField('Расход топлива, зима, норм. усл', default=0)
    rate_hard_w = models.FloatField('Расход топлива, зима тяж. усл', default=0)

    station = models.ForeignKey(
        Station,
        related_name='cars',
        verbose_name='Участок',
        null=True,
        on_delete=models.SET_NULL
    )
    fuel_balance = models.DecimalField(
        'Остаток бензина',
        max_digits=7,
        decimal_places=2,
        default=0
    )
    fuel = models.ForeignKey(
        Fuel,
        related_name='cars',
        verbose_name='Топливо',
        null=True,
        blank=True,
        on_delete=models.PROTECT
    )

    def __str__(self):
        return '{}: {}, номер: {}'.format(self.get_kind_display(), self.name, self.number or 'нет')

    def update_data(self, km=None, fuel=None):
        if km:
            self.mileage = km
        if fuel:
            self.fuel_balance = fuel
        self.available = True
        self.save()

    def full_name(self):
        return '{0} - {1}'.format(self.name, self.number)

    def get_rate(self, conditions):
        if conditions == 'SN':
            return self.rate_normal_s
        elif conditions == 'WN':
            return self.rate_normal_w
        elif conditions == 'SH':
            return self.rate_hard_s
        elif conditions == 'WH':
            return self.rate_hard_w

    class Meta:
        verbose_name = 'Автомобиль'
        verbose_name_plural = 'Автомобили'
        ordering = ['name', 'kind']


# Model of materials / Модель материалов

class MaterialCategory(models.Model):
    name = models.CharField('Наименование', max_length=100, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория материалов'
        verbose_name_plural = 'Категории материалов'


class Material(models.Model):
    name = models.CharField('Наименование', max_length=100, unique=True)
    units = models.ForeignKey(
        Units,
        related_name="materials",
        verbose_name="Еденицы измерения",
        null=True,
        on_delete=models.SET_NULL
        )
    quantity = models.DecimalField('Количество', max_digits=10, decimal_places=2, default=0)
    category = models.ForeignKey(
        MaterialCategory, 
        related_name="materials",
        verbose_name="Категория",
        blank=True,
        null=True,
        on_delete=models.PROTECT
        )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'


# Outfit events / Мероприятия (работы)

class OutfitEvent(models.Model):
    name = models.CharField('Название', max_length=500)
    description = models.TextField('Описание', max_length=500, blank=True)

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'
        ordering = ['name']

    def __str__(self):
        if self.description:
            return '{} ({})'.format(self.name, self.description)
        else:
            return self.name

    def full_name(self):
        return self.__str__()


# Model of waybill / Модель путевого листа
class Waybill(models.Model):
    CHOICES_OF_TYPE = (
        ('L', 'легкового автомобиля'),
        ('H', 'грузового автомобиля'),
    )
    departament = models.CharField(
        'Отдел',
        choices=DEPARTAMENTS,
        max_length=50,
        null=True
        )
    event = models.ForeignKey(
        OutfitEvent,
        related_name="waybills",
        verbose_name="Мероприятие",
        null=True,
        blank=True,
        on_delete=models.PROTECT
        )

    type_of = models.CharField(
        'Тип путевого листа',
        choices=CHOICES_OF_TYPE,
        max_length=50,
        null=True
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='waybills',
        verbose_name='Автор',
        null=True,
        on_delete=models.SET_NULL
    )
    station = models.ForeignKey(
        Station,
        related_name='waybills',
        verbose_name='Участок',
        null=True,
        on_delete=models.PROTECT
    )

primary_docs/views.py
import datetime
import json

from django.views.generic import CreateView, ListView, View, DetailView
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import PermissionDenied

from .models import Waybill, DriverTask
from .forms import WayBillForm, DriverTaskForm


class GetWayBills(ListView):
    context_object_name = 'waybills'
    model = Waybill
    template_name = 'primary_docs/waybills_list.html'


class GetWayBillDetail(DetailView):
    context_object_name = 'waybill'
    model = Waybill
    template_name = 'primary_docs/waybills_detail.html'


class NewWayBill(CreateView):
    form_class = WayBillForm
    template_name = 'primary_docs/waybill_new.html'
    success_url = '/docs/waybills/'

    def post(self, request, *args, **kwargs):
        if request.is_ajax():
            data = json.loads(request.body.decode('utf-8'))
            data['author'] = request.user.pk
            tasks_list = []
            for task in data['tasks']:
                task_form = DriverTaskForm(task)
                if task_form.is_valid():
                    new_task = task_form.save()
                    tasks_list.append(new_task.pk)
            data['tasks'] = tasks_list
            form = WayBillForm(data)
            if form.is_valid():
                waybill = form.save()
                if waybill.is_completed:
                    waybill.complete()
                else:
                    waybill.car.available = False
                    waybill.car.save()
                return HttpResponse(self.success_url, status=201)
            else:
                return JsonResponse(form.errors, content_type='application/json', status=406)
        else:
            return JsonResponse('Не верный запрос!', status=405)


class EditWayBill(View):
    form_class = WayBillForm
    model = Waybill
    template_name = 'primary_docs/waybill_new.html'
    success_url = '/docs/waybills/'

    def get(self, request, pk, *args, **kwargs):
        waybill = get_object_or_404(Waybill, pk=pk)
        if not waybill.is_completed and request.user.is_staff:
            return render(request, self.template_name)
        else:
            msg = 'Недостаточно прав' if not request.user.is_staff else 'Путевой лист завершен'
            raise PermissionDenied(msg)

    def post(self, request, pk, *args, **kwargs):
        waybill = get_object_or_404(Waybill, pk=pk)
        if not waybill.is_completed and request.user.is_staff:
            if request.is_ajax:
                data = json.loads(request.body.decode('utf-8'))
                data['author'] = request.user.pk
                tasks_list = []
                for task in data['tasks']:
                    task_form = DriverTaskForm(task)
                    if task_form.is_valid():
                        new_task, created = DriverTask.objects.get_or_create(**task_form.cleaned_data)
                        tasks_list.append(new_task.pk)
                data['tasks'] = tasks_list
                form = WayBillForm(data, instance=waybill)
                if form.is_valid():
                    waybill = form.save()
                    if waybill.is_completed:
                        waybill.complete()
                    else:
                        waybill.car.available = False
                        waybill.car.save()
                    return HttpResponse(self.success_url, status=200)
                return JsonResponse(form.errors, content_type='application/json', status=409)
            else:
                return JsonResponse('Не верный запрос!', status=405)
        else:
            msg = 'Недостаточно прав' if not request.user.is_staff else 'Путевой лист завершен'
            raise PermissionDenied(msg)


def print_waybill(request, pk):
    waybill = get_object_or_404(Waybill, pk=pk)
    if waybill.is_completed:
        return render(request, waybill.get_template, {'wb': waybill})
    else:
        raise PermissionDenied('Путевой лист не завершен')

taskmaster/views.py
# views

taskmaster/templates/primary_docs/waybill_new.html
<!DOCTYPE html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>Путевой лист</title><link rel=stylesheet href=https://unpkg.com/element-ui/lib/theme-chalk/index.css><link href=/static/css/app.6b1af04775d9333067e9db4120c484ef.css rel=stylesheet></head><style>body, html {margin: 0; padding: 0; height: 100%;}</style><body><div id=app></div><script type=text/javascript src=/static/js/manifest.2bc0df20003a6dc7f889.js></script><script type=text/javascript src=/static/js/vendor.37c31dc3b44decea73d1.js></script><script type=text/javascript src=/static/js/app.95a6f96a140be47fa9a5.js></script></body></html>

taskmaster/templates/primary_docs/waybills_detail.html
<div class="modal-dialog modal-lg" role="document">
	<div class="modal-content">
	  <div class="modal-header bg-primary text-white">
		<h5 class="modal-title mx-auto" id="waybill-title">Путевой лист {{ waybill.get_type_of_display }} № {{ waybill.number }}</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	  </div>
	  <div class="modal-body px-3 py-0">
		<div class="card table-bordered text-left" id="waybill_detail_view">
			<h5 class="card-header">Основные данные</h5>
			<div class="row">
				<div class="col-md-6">
					Организация:
				</div>
				<div class="col-md-6">
					{{ waybill.organization }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Участок:
				</div>
				<div class="col-md-6">
					{{ waybill.station }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Оператор:
				</div>
				<div class="col-md-6">
					{{ waybill.author.get_full_name }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Дата:
				</div>
				<div class="col-md-6">
					{{ waybill.date}}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Номер:
				</div>
				<div class="col-md-6">
					{{ waybill.number }}
				</div>
			</div>	
			<div class="row">
				<div class="col-md-6">
					Автомобиль:
				</div>
				<div class="col-md-6">
					{{ waybill.car }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Статус:
				</div>
					<div class="col-md-6">
					{% if waybill.is_completed %}
						<i class="fa fa-check text-success"></i>
						{% else %}
						<i class="fa fa-spin fa-hourglass-end text-warning"></i>
					{% endif %}
					</div>
			</div>
			<h5 class="card-header">Персонал</h5>
			<div class="row">
				<div class="col-md-6">
					Водитель:
				</div>
				<div class="col-md-6">
					{{ waybill.driver }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Диспетчер:
				</div>
				<div class="col-md-6">
					{{ waybill.dispatcher|default_if_none:'---' }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Выезд разрешен:
				</div>
				<div class="col-md-6">
					{{ waybill.check_out_allow }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Автомобиль принял:
				</div>
				<div class="col-md-6">
					{{ waybill.car_took }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Сдал водитель:
				</div>
				<div class="col-md-6">
					{{ waybill.auto_passed }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Принял механик:
				</div>
				<div class="col-md-6">
					{{ waybill.auto_accept }}
				</div>
			</div>
			<h5 class="card-header">Движение горючего</h5>
			<div class="row">
				<div class="col-md-6">
					Горючее:
				</div>
				<div class="col-md-6">
					{{ waybill.fuel }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Остаток при выезде:
				</div>
				<div class="col-md-6">
					{{ waybill.fuel_balance_on_dep }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Остаток при возвращении:
				</div>
				<div class="col-md-6">
					{{ waybill.fuel_balance_on_ret }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Выданно л:
				</div>
				<div class="col-md-6">
					{{ waybill.fuel_issued }}
				</div>
			</div>
			<h5 class="card-header">Работа водителя и автомобиля</h5>
			<div class="row">
				<div class="col-md-6">
					Выезд из гаража:
				</div>
				<div class="col-md-6">
					{{ waybill.dep_date }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					Возвращение в гараж:
				</div>
				<div class="col-md-6">
					{{ waybill.ret_date }}
				</div>
			</div>
			<h6 class="card-header p-1">Показания спидометра</h6>
			<div class="row">
				<div class="col-md-6">
					При выезде:
				</div>
				<div class="col-md-6">
					{{ waybill.dep_km }}
				</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					При возвращении:
				</div>
				<div class="col-md-6">
					{{ waybill.ret_km }}
				</div>
			</div>
			<h5 class="card-header">Задания водителю</h5>
			<table class="table table-sm text-center">
				<thead>
					<tr>
						<th>#</th>
						<th>Из</th>
						<th>В</th>
						<th>Выезд</th>
						<th>Возвр.</th>
						<th>Км</th>
						<th>Расход</th>
						<th>Вид работ</th>
						<th>Условия</th>
					</tr>
				</thead>
				<tbody style="font-size:8pt;">
			{% for task in waybill.tasks.all %}
				<tr>
					<td> {{ forloop.counter }}</td>
					<td>{{ task.from_dest}}</td>
					<td>{{ task.to_dest }}</td>
					<td>{{ task.departure|date:'d.m.y H:i' }}</td>
					<td>{{ task.arrival|date:'d.m.y H:i' }}</td>
					<td>{{ task.distance }}</td>
					<td>{{ task.total_fuel }}</td>
					<td>{{ task.kind }}</td>
					<td>{{ task.get_conditions_display }}</td>
				</tr>		
			{% endfor %}
			</tbody>
				<tfoot class="table-active">
					<tr>
						<th colspan='3'>Итого:</th>
						<td colspan='2'>{{ waybill.total_hours }} часов</td>
						<td>{{ waybill.total_km }}</td>
						<td>{{ waybill.total_fuel }}</td>
						<td></td>
						<td></td>
					</tr>
				</tfoot>
			</table>
			<div class="row">
				<div class="col-md-6">
					Особые отметки:
				</div>
				<div class="col-md-6">
					{{ waybill.comment }}
				</div>
			</div>
	</div>	
	 </div>
	
		<div class="modal-footer">
			 {% if waybill.is_completed %}
				<button type="button" role="button" class="btn btn-primary fa fa-print mr-auto"> <a href="{% url 'print_waybill' pk=waybill.pk %}" target='_blank' style="text-decoration:none;" class="text-white">Печать</a></button>
			{% else %}
				<button role="button" class="btn btn-primary mr-auto"><a href="{% url 'edit_waybill' pk=waybill.pk %}#msform" style="text-decoration:none;" class="text-white">Редактировать</a></button>
			{% endif %}
			<button type="button" class="btn btn-danger" role="button" data-dismiss="modal">Закрыть</button>
		</div>
	</div>
</div>

taskmaster/templates/primary_docs/waybills_list.html
{% extends 'taskmaster/base.html' %}

{% block title %}
	Путевые листы
{% endblock title %}

{% block content %}
	<div id="waybill-options" class="p-2">
		<a href=" {% url 'new_waybill' %}" target="blank" style="position: absolute; left: 10px;" class="px-3 btn btn-sm btn-outline-success" data-toggle='tooltip'data-placement="right" title='Создать новый'><i class="fa fa-plus p-0"></i></a>
		<span class="mr-5">Путевые листы</span>
	</div>
    <div class="table-responsive">
	<table class="table" id="wayBillsListTable">
		<thead class="table-active">
            <tr>
				<th>#</th>
				<th>№</th>
				<th>Участок</th>
				<th>Тип</th>
				<th>Дата</th>
				<th>Автомобиль</th>
				<th>Водитель</th>
				<th>Задачи</th>
				<th>Всего км</th>
				<th>Часы</th>
				<th>Топливо, л.</th>
				<th>Статус</th>
				<th>Опции</th>
			</tr>
		</thead>
		<tbody id="waybills_list">
			{% for wb in waybills|dictsortreversed:"date" %}
				<tr data-pk="{{ wb.pk }}">
					<td>{{ forloop.counter }}</td>
					<td>{{ wb.number }}</td>
					<td>{{ wb.station }}</td>
					<td>{{ wb.get_type_of_display.0|upper }}</td>
					<td>{{ wb.date }}</td>
					<td>{{ wb.car }}</td>
					<td>{{ wb.driver }}</td>
					<td>{{ wb.tasks.count }}</td>
					<td>{{ wb.total_km }}</td>
					<td>{{ wb.total_hours }}</td>
					<td>{{ wb.total_fuel }}</td>
					<td>
					{% if wb.is_completed %}
						<i class="fa fa-check text-success" title="Завершен"></i>
					{% else %}
						<i class="fa fa-spin fa-hourglass-end text-warning"></i>
					{% endif %}
					</td>
					<td>
						<div class="dropdown">
							<i class="btn text-primary dropdown-toggle fa fa-lg fa-list" id="dropdownMenuButton" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
							<ul class="dropdown-menu dropdown-menu-right" aria-lebelleby="dropdownMenuButton">
								<li role="button" class="btn btn-sm text-primary dropdown-item px-0" onclick='viewWaybill("{{wb.pk}}")'><i class="dropdown-item fa fa-fw fa-eye text-primary"></i> Просмотр</li>
								{% if not wb.is_completed %}
									<li role="button" class="btn btn-sm text-primary dropdown-item px-0"><a href="{% url 'edit_waybill' pk=wb.pk %}#msform" style="text-decoration:none;"><i class="dropdown-item fa fa-fw fa-edit text-primary"></i> Редактировать</a></li>
								{% else %}
									<li role="button" class="btn btn-sm text-primary dropdown-item px-0"><a href="{% url 'print_waybill' pk=wb.pk %}" target='_blank' style="text-decoration:none;" onClick="printWayBill()"><i class="dropdown-item fa fa-fw fa-print text-primary"></i> Печать</a></li>
								{% endif %}
							</ul>
						</div>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	</div>
<div class="modal fade bd-example-modal-lg" id="waybillView" role="dialog">

  </div>

{% endblock content %}